//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.VilaniTranslatorServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VilaniTranslatorServices.IVilaniTranslatorServices")]
    public interface IVilaniTranslatorServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/TranslateStringArray", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/TranslateStringArrayResponse")]
        string[] TranslateStringArray(string[] inputParams, string sourceLanguage, string destinationLanaguge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/TranslateStringArray", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/TranslateStringArrayResponse")]
        System.Threading.Tasks.Task<string[]> TranslateStringArrayAsync(string[] inputParams, string sourceLanguage, string destinationLanaguge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglish", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglishResponse")]
        System.Collections.Generic.Dictionary<string, string> ConvertToEnglish(System.Collections.Generic.Dictionary<string, string> inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglish", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglishResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> ConvertToEnglishAsync(System.Collections.Generic.Dictionary<string, string> inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglishArray", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglishArrayResponse")]
        string[] ConvertToEnglishArray(string[] inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglishArray", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToEnglishArrayResponse")]
        System.Threading.Tasks.Task<string[]> ConvertToEnglishArrayAsync(string[] inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathi", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathiResponse")]
        System.Collections.Generic.Dictionary<string, string> ConvertToMarathi(System.Collections.Generic.Dictionary<string, string> inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathi", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathiResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> ConvertToMarathiAsync(System.Collections.Generic.Dictionary<string, string> inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathiArray", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathiArrayResponse")]
        string[] ConvertToMarathiArray(string[] inputParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathiArray", ReplyAction="http://tempuri.org/IVilaniTranslatorServices/ConvertToMarathiArrayResponse")]
        System.Threading.Tasks.Task<string[]> ConvertToMarathiArrayAsync(string[] inputParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVilaniTranslatorServicesChannel : ConsoleApplication1.VilaniTranslatorServices.IVilaniTranslatorServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VilaniTranslatorServicesClient : System.ServiceModel.ClientBase<ConsoleApplication1.VilaniTranslatorServices.IVilaniTranslatorServices>, ConsoleApplication1.VilaniTranslatorServices.IVilaniTranslatorServices {
        
        public VilaniTranslatorServicesClient() {
        }
        
        public VilaniTranslatorServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VilaniTranslatorServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilaniTranslatorServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VilaniTranslatorServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] TranslateStringArray(string[] inputParams, string sourceLanguage, string destinationLanaguge) {
            return base.Channel.TranslateStringArray(inputParams, sourceLanguage, destinationLanaguge);
        }
        
        public System.Threading.Tasks.Task<string[]> TranslateStringArrayAsync(string[] inputParams, string sourceLanguage, string destinationLanaguge) {
            return base.Channel.TranslateStringArrayAsync(inputParams, sourceLanguage, destinationLanaguge);
        }
        
        public System.Collections.Generic.Dictionary<string, string> ConvertToEnglish(System.Collections.Generic.Dictionary<string, string> inputParams) {
            return base.Channel.ConvertToEnglish(inputParams);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> ConvertToEnglishAsync(System.Collections.Generic.Dictionary<string, string> inputParams) {
            return base.Channel.ConvertToEnglishAsync(inputParams);
        }
        
        public string[] ConvertToEnglishArray(string[] inputParams) {
            return base.Channel.ConvertToEnglishArray(inputParams);
        }
        
        public System.Threading.Tasks.Task<string[]> ConvertToEnglishArrayAsync(string[] inputParams) {
            return base.Channel.ConvertToEnglishArrayAsync(inputParams);
        }
        
        public System.Collections.Generic.Dictionary<string, string> ConvertToMarathi(System.Collections.Generic.Dictionary<string, string> inputParams) {
            return base.Channel.ConvertToMarathi(inputParams);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> ConvertToMarathiAsync(System.Collections.Generic.Dictionary<string, string> inputParams) {
            return base.Channel.ConvertToMarathiAsync(inputParams);
        }
        
        public string[] ConvertToMarathiArray(string[] inputParams) {
            return base.Channel.ConvertToMarathiArray(inputParams);
        }
        
        public System.Threading.Tasks.Task<string[]> ConvertToMarathiArrayAsync(string[] inputParams) {
            return base.Channel.ConvertToMarathiArrayAsync(inputParams);
        }
    }
}
