//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vilani.BackroundService.PublicServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublicServices.IPublicServices")]
    public interface IPublicServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicServices/GeneratePlottingStatusReport", ReplyAction="http://tempuri.org/IPublicServices/GeneratePlottingStatusReportResponse")]
        int GeneratePlottingStatusReport(string securityCode, System.DateTime statusDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicServices/GeneratePlottingStatusReport", ReplyAction="http://tempuri.org/IPublicServices/GeneratePlottingStatusReportResponse")]
        System.Threading.Tasks.Task<int> GeneratePlottingStatusReportAsync(string securityCode, System.DateTime statusDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicServicesChannel : Vilani.BackroundService.PublicServices.IPublicServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicServicesClient : System.ServiceModel.ClientBase<Vilani.BackroundService.PublicServices.IPublicServices>, Vilani.BackroundService.PublicServices.IPublicServices {
        
        public PublicServicesClient() {
        }
        
        public PublicServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GeneratePlottingStatusReport(string securityCode, System.DateTime statusDate) {
            return base.Channel.GeneratePlottingStatusReport(securityCode, statusDate);
        }
        
        public System.Threading.Tasks.Task<int> GeneratePlottingStatusReportAsync(string securityCode, System.DateTime statusDate) {
            return base.Channel.GeneratePlottingStatusReportAsync(securityCode, statusDate);
        }
    }
}
